;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        haml-electric-backspace
        paredit-forward-delete
        paredit-reindent-defun
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        paredit-semicolon
        smex
        ))
